# ========== ???????? ==========
spring.application.name=warehouse-backend

# ========== ???? ?????? (PostgreSQL) ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/warehouse
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== HIBERNATE (JPA) ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========== ??????????? ==========
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.warehouse=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.com.warehouse.warehouse_backend=DEBUG

## ========== JWT ==========
#jwt.secret=yourSecretKeyForJwtToken1234567890abcdefghijklmnopqrstuvwxyz
#jwt.expiration=86400000  # 24 ???? ? ?????????????
#jwt.refresh-expiration=604800000  # 7 ????
#
# ========== CORS (??? Vue) ==========
app.frontend.url=http://localhost:5173

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=borowikoviwan1901@gmail.com
#spring.mail.password=bcrq fgpg felm sjis
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

## ????????????? ????? ????????? ????????, ????? ???????? ?????????[reference:16]
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=3000
#spring.mail.properties.mail.smtp.writetimeout=5000

# ========== EMAIL (Mailtrap Sandbox) ==========
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=25
spring.mail.username=233f79835422e4
spring.mail.password=13a5470bace18b

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000